# Generated by Django 5.0.4 on 2024-04-23 15:03

import uuid

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Video's id",
                    ),
                ),
                (
                    "video",
                    models.FileField(
                        null=True,
                        upload_to="videos/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=("mp4",)
                            )
                        ],
                        verbose_name="Video's location",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="Video's original name"
                    ),
                ),
            ],
        ),
    ]
