# Generated by Django 5.0.4 on 2024-04-25 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("video", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="video",
            old_name="video",
            new_name="file",
        ),
        migrations.AddField(
            model_name="video",
            name="is_processing",
            field=models.BooleanField(
                default=False, verbose_name="Is video being processed?"
            ),
        ),
        migrations.AddField(
            model_name="video",
            name="last_processed_success",
            field=models.BooleanField(
                default=None,
                null=True,
                verbose_name="Was last processing of video successful?",
            ),
        ),
    ]
